<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <NodeReuse>false</NodeReuse>
    <UseSharedCompilation>false</UseSharedCompilation>
    <!-- Suprime CS1591: comentário XML ausente para membros públicos -->
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
</Project>
